### ISSUE TITLE
Errors when running tool

### ISSUE THREAD

**Issue by roblohmann** [microsoft/azure-artifacts-migration#4]
I just followed the steps as provided on https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/migrate-packages?view=azure-devops. The only thing different is that I'm running this in an Azure Cloud Shell

However, I'm getting a lot of errors when first running the migration. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/19424841/74234921-40103780-4cce-11ea-8995-994ef8d93634.png)

**Comment by chasewilson** [comment]
Hi @roblohmann , Thanks for the feedback. This isn't tested for Azure CloudShell. This module requires the Nuget CLI and a location to temporarily store migrating packages. I don't believe you can use the Cloud Shell for this at all.  Feel free to correct me if I'm wrong and we can work towards a solution.

**Comment by roblohmann** [comment]
> Hi @roblohmann , Thanks for the feedback. This isn't tested for Azure CloudShell. This module requires the Nuget CLI and a location to temporarily store migrating packages. I don't believe you can use the Cloud Shell for this at all. Feel free to correct me if I'm wrong and we can work towards a solution.

Hi @chasewilson , thank you for the reply. I understand why it isn't designed for and thus not working in the CloudShell. Never got this working, so I've chosen a different approach and just downloaded the packages to my local computer and used a small script to push them to the new artifacts repository.

**Comment by chasewilson** [comment]
@roblohmann I'm glad it worked out for you. Essentially that's what the module does anyways. If you have any suggestions on the documentation or the implementation, feel free to throw it out there!

**Comment by eloekset** [comment]
Can we reopen this issue? Any idea why we're getting these error messages?
